### PR TITLE
Add basic mock apollo server

### PR DESCRIPTION
**Pull request by joshxg**
Just went with the easy, javascript with babel node and nodemon option .. tried to get typescript working but I gave up super quick

### CODE REVIEW

**Comment by joshxg** [comment]
This is cute 

image

**Comment by joshxg** [comment]
Actually getting ts errors in the js files which is annoying, going to take a look at that

**Comment by joshxg** [comment]
Sorry! Good to go now.

I'm not sure what to do about the fields of a transaction. I'd like to have the 'real' field names we'll have in the future, but that discussion seems to be .. ongoing.. so will just go with this for now 🤷

**Review by mark-prins — APPROVED** [review]
👍  love it!
The `faker` is huuge - but awesome.

**Pull request merged**
